# Generated by Django 4.1.7 on 2023-07-26 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flawsapp', '0002_remove_urlnotes_id_urlnotes_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlnotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
