name: Lint and test code, and if OK, build and deploy Docker image to Fly.io
on:
  push:
    branches:
      - main
    paths:
      - "secprojectI/**"

jobs:
  lint-and-test:
    name: Run Pylint and Django tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint_django django pytest pytest-django
        python secprojectI/manage.py check 


    - name: Run Pylint
      run: |
        pylint --load-plugins=pylint_django --django-settings-module=secprojectI.settings secprojectI/flawsapp/ 
      continue-on-error: false  # Fail the job if Pylint returns errors

    - name: Run migrations
      run: |
        python secprojectI/manage.py migrate

    - name: Run Django tests
      run: |
        python secprojectI/manage.py test flawsapp
      continue-on-error: false  # Fail the job if tests return errors
  
  build-and-deploy:
    needs: lint-and-test
    name: Build Docker image and deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js version 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kumpula-app:latest


    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      run: flyctl deploy --image ${{ secrets.DOCKERHUB_USERNAME }}/kumpula-app:latest --app kumpula-app
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [lint-and-test, build-and-deploy]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} && ${{ !contains(join(toJson(github.event.commits.*.message), ' '), '#skip') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DEFAULT_BUMP: patch
