name: Build and deploy Docker image to Fly.io
on:
  push:
    branches:
      - main
    paths:
      - "secprojectI/**"

jobs:
  build-and-deploy:
    name: Build Docker image and deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kumpula-app:latest

    - name: Install Fly cli
      run: |
        curl -L https://fly.io/install.sh | sh
        export PATH=$HOME/.fly/bin:$PATH

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl auth token $FLY_API_TOKEN
        flyctl deploy --image ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest --app kumpula-name
