name: Scheduled jobs 
on:
    schedule:
        - cron: "0 8 * * *"
jobs:
    url_check:
        runs-on: ubuntu-20.04
        steps:
          - name: Ping URL
            uses: jtalk/url-health-check-action@v4
            with:
                url: ${{ vars.HEALTH_CHECK_URL }}
